# Generated by Django 5.1.4 on 2024-12-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_deathrecord_eggsale_feeddata_hatchdata_otherexpenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherexpenses',
            old_name='other_expense',
            new_name='expense_type',
        ),
    ]
