# Generated by Django 5.1.4 on 2024-12-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_other_expense_otherexpenses_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='kilograms',
            field=models.FloatField(),
        ),
    ]
